### PR TITLE
Added Share-Button

### PR DESCRIPTION
**Pull request by ps100000**
Added button that allows the user to share the number of blocked ads/trackers.

### CODE REVIEW

**Comment by animeking9901** [comment]
Hasn't this been a request for a while? I see no issues here

**Comment by ps100000** [comment]
Yes, this has been requested here: #160

**Comment by Thomas499** [comment]
<string name="social_share_body">Blokada blocked %s ads and trackers in the last %s! If you want to get rid of ads too go to blokada.org and get the app now!</string> Might be a good idea to mention blokada is for android only. Don't want to waste peoples time who are interested in blocking ads but have apple phones. Recommended: <string name="social_share_body">Blokada blocked %s ads and trackers in the last %s! If you have an android device and want to get rid of ads too go to blokada.org and get the app now!</string>

**Comment by ps100000** [comment]
The text was meant to be more of a placeholder anyway. I would rather leave the final wording to someone who has English as his mother language.

**Pull request merged**
