### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Update gradle wrapper to 6.5 using git bash

### 2nd commit
- Update .gitignore to include all build files
- Update Android Studio 3.5.3 -> 4.0.0 ([changelog](https://developer.android.com/studio/releases))
- Update Kotlin 1.3.30 -> 1.3.72 ([changelog](https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md))
- `com.gladed.androidgitversion` 0.4.7 -> 0.4.13 ([commits since 0.4.7](https://github.com/gladed/gradle-android-git-version/releases))
- Use Kotlin JDK8

### 3rd commit
- Update AndroidX appcompat 1.0.2 -> 1.1.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/appcompat))
- Turn customtabs into AndroidX browser 1.2.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/browser))
- Update Google material 1.0.0 -> 1.1.0 ([changelog](https://github.com/material-components/material-components-android/releases))
- Update kotlinx-coroutines-android 0.23.1 -> 0.23.4 ([changelog](https://github.com/Kotlin/kotlinx.coroutines/blob/master/CHANGES.md))
- Update paperdb 2.6 -> 2.7.1 ([changelog](https://github.com/pilgr/Paper/releases))
- Update pcap4j 1.7.0 -> 1.7.7 ([changelog](https://github.com/kaitoy/pcap4j/blob/v1/CHANGES.md))
- Update dnsjava 2.1.8 -> 3.1.0 ([changelog](https://github.com/dnsjava/dnsjava/blob/master/Changelog))
- Remove unused slf4j dependency
- Update folding-cell 1.2.2 -> 1.2.3 ([changelog](https://github.com/Ramotion/folding-cell-android/commits/master))
- Update stickyswitch 0.0.15 -> 0.0.16 ([changelog](https://github.com/GwonHyeok/StickySwitch/releases))
- Update okhttp 3.14.0 -> 3.14.9 ([changelog](https://square.github.io/okhttp/changelog_3x/))
- Update retrofit 2.5.0 -> 2.9.0 ([changelog](https://github.com/square/retrofit/blob/master/CHANGELOG.md))
- Update test dependencies

### CODE REVIEW

**Comment by TacoTheDank** [comment]
https://github.com/blokadaorg/blokada/pull/689#issuecomment-642527518_

**Comment by TacoTheDank** [comment]
@kar Any updates?

**Comment by kar** [comment]
Thanks @TacoTheDank for this very well-prepared PR. While building, I got a few minor build errors, seems like mostly related to Retrofit update?

```
➜  blokada git:(pr733) ./gradlew aFB

> Task :app:compileFullBetaKotlin FAILED
...
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/official/kotlin/buildtype/JournalClient.kt: (119, 40): Type mismatch: inferred type is (???, ???) -> Boolean but HostnameVerifier was expected
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/official/kotlin/buildtype/JournalClient.kt: (119, 42): Cannot infer a type for this parameter. Please specify it explicitly.
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/official/kotlin/buildtype/JournalClient.kt: (119, 52): Cannot infer a type for this parameter. Please specify it explicitly.
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/official/kotlin/buildtype/JournalClient.kt: (856, 43): Using 'body(): ResponseBody?' is an error. moved to val
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/official/kotlin/buildtype/JournalClient.kt: (878, 33): Using 'code(): Int' is an error. moved to val
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/tun-local/kotlin/blocka/Retrofit.kt: (17, 48): Using 'url(): HttpUrl' is an error. moved to val
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/tun-local/kotlin/blocka/Retrofit.kt: (20, 51): Using 'method(): String' is an error. moved to val
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/tun-local/kotlin/blocka/Retrofit.kt: (21, 48): Using 'url(): HttpUrl' is an error. moved to val
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/tun-local/kotlin/blocka/Retrofit.kt: (26, 44): Using 'url(): HttpUrl' is an error. moved to val
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/tun-local/kotlin/blocka/Retrofit.kt: (47, 74): Using 'url(): HttpUrl' is an error. moved to val
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/tun-local/kotlin/blocka/Retrofit.kt: (64, 52): Using 'url(): HttpUrl' is an error. moved to val
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/tun-local/kotlin/blocka/Retrofit.kt: (67, 55): Using 'method(): String' is an error. moved to val
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/tun-local/kotlin/blocka/Retrofit.kt: (68, 52): Using 'url(): HttpUrl' is an error. moved to val
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/tun-local/kotlin/blocka/Retrofit.kt: (73, 48): Using 'url(): HttpUrl' is an error. moved to val
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/tun-local/kotlin/blocka/Retrofit.kt: (80, 44): Using 'url(): HttpUrl' is an error. moved to val
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/tun-local/kotlin/blocka/Retrofit.kt: (99, 70): Using 'url(): HttpUrl' is an error. moved to val
e: /Users/kar/code/github.com/blokadaorg/blokada/app/src/tun-local/kotlin/blocka/Retrofit.kt: (111, 66): Using 'url(): HttpUrl' is an error. moved to val
```

**Comment by TacoTheDank** [comment]
@kar Should be good now!

**Comment by kar** [comment]
Thank you, it seems fine now. I was able to compile and run the app without problems.

**Pull request merged**
