### PR TITLE
Update dependencies and codestyle

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Update gradle wrapper to 6.3 using git bash

### 2nd commit
- Update .gitignore to include all build files
- Add ndkVersion to fix build error
- Update Android Studio 3.5.1 -> 3.6.3 ([changelog](https://developer.android.com/studio/releases))
- Update Kotlin 1.3.30 -> 1.3.72 ([changelog](https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md))
- `com.gladed.androidgitversion` 0.4.7 -> 0.4.13 ([commits since 0.4.7](https://github.com/gladed/gradle-android-git-version/releases))
- Use Kotlin JDK8

### 3rd commit
- Update AndroidX appcompat 1.0.2 -> 1.1.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/appcompat))
- Turn customtabs into AndroidX browser 1.2.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/browser))
- Update Google material 1.0.0 -> 1.1.0 ([changelog](https://github.com/material-components/material-components-android/releases))
- Update kotlinx-coroutines-android 0.23.1 -> 0.23.4 ([changelog](https://github.com/Kotlin/kotlinx.coroutines/blob/master/CHANGES.md))
- Update pcap4j 1.7.0 -> 1.7.7 ([changelog](https://github.com/kaitoy/pcap4j/blob/v1/CHANGES.md))
- Update dnsjava 2.1.8 -> 3.0.2 ([changelog](https://github.com/dnsjava/dnsjava/blob/master/Changelog))
- Remove unused slf4j dependency
- Update folding-cell 1.2.2 -> 1.2.3 ([changelog](https://github.com/Ramotion/folding-cell-android/commits/master))
- Update stickyswitch 0.0.15 -> 0.0.16 ([changelog](https://github.com/GwonHyeok/StickySwitch/releases))
- Update okhttp 3.14.0 -> 3.14.7 ([changelog](https://square.github.io/okhttp/changelog_3x/))
- Update retrofit 2.5.0 -> 2.8.1 ([changelog](https://github.com/square/retrofit/blob/master/CHANGELOG.md))
- Update test dependencies

### 4th commit
- Migrate codestyle to Kotlin's official

### 5th commit
- Clean up imports

### CODE REVIEW

**Comment by kar** [comment]
@TacoTheDank hi mate, may I know why did you close your PR? I couldn't include it this time in, but was going to merge it for the 4.7.

**Comment by TacoTheDank** [comment]
@kar I actually cannot remember, lol. Looking at the commits, there's a few things that I realize now didn't have to be done, but I don't think that's why I closed it.

**Comment by TacoTheDank** [comment]
@kar However, I am going to reference [this issue](https://github.com/blokadaorg/blokada/issues/473), which I believe is still of very high priority as should be done ASAP.

**Comment by kar** [comment]
@TacoTheDank Any chance you'd prepare at least some of the updates? I'll make sure it gets merged.

**Comment by TacoTheDank** [comment]
@kar I might

**Pull request closed without merging**
